### ISSUE TITLE
NodeChecker thread causing Tomcat to hang during shutdown

### ISSUE THREAD

**Issue by mkurian** [searchbox-io/Jest#167]
I'm using 0.1.1 version of jest client. 

The only option to configure discovery check is to set frequency. It would be ideal to have the NodeChecker configured to be a daemon thread. The issue is that, when tomcat server shuts down, this thread is still alive and prevents the process to gracefully die.

If there is a workaround or a feature that I might have missed, please let me know.

**Comment by kramer** [comment]
Flagging it as daemon is not a solution because then (yes your main process would gracefully die but)  `NodeChecker` would just keep living in the background.

Other points to consider are:
* You should be calling `JestClient.shutdownClient()` during shutdown which will terminate discovery and idle-connection-reaper services.
* Even without calling the shutdown method things seems to be fine as `JestClientFactoryIntegrationTest` is testing both discovery and idle-connection-reaper services and it is exiting normally (unless JUnit has some force stop feature that I don't know).

**Comment by kramer** [comment]
Closing this issue as no update was made in a long time. Please feel free to reopen if you come up with any new information.
