### ISSUE TITLE
Multisearch is not formatted correctly

### ISSUE THREAD

**Issue by hlassiege** [searchbox-io/Jest#245]
I'm not sure exactly if I use multisearch correctly but I've a request produced by Jest like this : 

```
{"index" : "test", "type" : "test"}
{
    "query" : {
        "query" : { 
          "match_all" : {} 
        }
    }
}
```
However, this is not correct, it should have been 

```
{"index" : "test", "type" : "test"}
{ "query" : {      "match_all" : {}         }}

```
(Everything on the same line, only one query)

I used a query build to build the Search into the Multisearch object : 

List<Search> searches = new ArrayList<>();
// build Searches
MultiSearch multiSearch = new MultiSearch.Builder(searches).build();

Any idea what could be wrong ?

**Comment by kramer** [comment]
See [MultiSearchIntegrationTest](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/MultiSearchIntegrationTest.java#L32) for example usage.

You are right that query should be on a single line and it is user's responsibility to provide it without line breaks to Jest just as they would do to ES. There is no line break replacement on Jest side to counter this because it's bit of a destructive process that could potentially effect the actual data.

As for the fact that `query` element is present twice: the outer `query` element inserted by `MultiSearch` should not have been there, probably result of an assumption carried out from past, I have fixed that now.
