### ISSUE TITLE
Open HttpClientBuilder creation for extension?

### ISSUE THREAD

**Issue by bacar** [searchbox-io/Jest#275]
I'd like to use `WinHttpClients` instead of `HttpClients` to create the `HttpClientBuilder` as described here: http://stackoverflow.com/a/22865583/37941

Is it a good idea to open the current direct call to `HttpClients.custom` for extension? Here's the current code.

```
private CloseableHttpClient createHttpClient(HttpClientConnectionManager connectionManager) {
    return configureHttpClient(
            HttpClients.custom()
                    .setConnectionManager(connectionManager)
                    .setDefaultRequestConfig(getRequestConfig())
                    .setProxyAuthenticationStrategy(httpClientConfig.getProxyAuthenticationStrategy())
                    .setRoutePlanner(getRoutePlanner())
                    .setDefaultCredentialsProvider(httpClientConfig.getCredentialsProvider())
    ).build();
}
```

(it's possible there's a solution to this already through one of the existing extensibility points but if so I can't see it. I'm new to Apache HC & Jest).

**Comment by bacar** [comment]
For now I've got it working with:

	factory = new JestClientFactory() {
		 @Override
		protected HttpClientBuilder configureHttpClient(HttpClientBuilder builder) {
			 return
	            WinHttpClients.custom()
	                .setConnectionManager(getConnectionManager())
	                .setDefaultRequestConfig(getRequestConfig())
	                .setRoutePlanner(getRoutePlanner());
		 	}
		 
	 };			
			
But it's sad that I have to duplicate the three sets from the base class (and I couldn't figure out a way to get the clientconfig details - ProxyAuthenticationStrategy/DefaultCredentialsProvider - I'm not sure how these would/should be affected by choosing a different client builder that's ment to handle auth though.

Also note that async support doesn't seem to be present in `WinHttpClients`.

**Comment by kramer** [comment]
As `JestClientFactory` currently stands I don't see any solution that can go beyond the workaround code you provided. 

As a feature extension point `HttpClients.custom()` and `HttpAsyncClients.custom()` could be replaced with `protected HttpClientBuilder GetHttpClientBuilder()` and `protected HttpAsyncClientBuilder GetAsyncHttpClientBuilder` methods but:
- it would create pollution coexisting with `configureHttpClient` methods - so maybe they should be removed (as replaced with the new methods) and that would be a nasty breaking change for, well, no gain to the average user
- and I'm not sure how useful it would be in the end; because this class is intended and quite hard wired to the standard `HttpClient` - instead it could be more logically sound and efficient to just create a new factory of `JestWinHttpClientFactory` which caters to the specific (configuration) needs of `WinHttpClient`.


> I'm not sure how these would/should be affected by choosing a different client builder that's meant to handle auth though.

Unfortunately I have no experience with `WinHttpClient` so my guess is as good as yours.

**Comment by bacar** [comment]
> this class is intended and quite hard wired to the standard HttpClient 

It's not clear to me how this manifests itself (and why the WinHttp one isn't a drop in replacement), but I don't know Apache HC at all so I'll take your word for it for now!

I think WinHttpClient is fairly immature so probably best to park this for now anyway.
