### ISSUE TITLE
Mitigating a slow ES cluster node slowing down the whole app.

### ISSUE THREAD

**Issue by andrejserafim** [searchbox-io/Jest#281]
Hi,

Right now jest takes the server list (manually configured or discovered) and iterates over it in a circular manner per request. This is done in the AbstractJestClient if I am not mistaken.

What happens if we have several threads inserting data into elasticsearch on the client and one of the elasticsearch nodes is slow (e.g. disk issues). The throughput of the whole app slows down several times - since there's no way to tell that our slow node is way behind and therefore we should skip it for the next request.

Have other folks seen this? Any thoughts on a sensible solution?

**Comment by kramer** [comment]
What you are asking, if I understood correctly, is a kind of load balancing (or intelligent routing) which jest does not have built in.

A starting point would be overriding the `AbstractJestClient.setServers(Set<String> servers)` method to set a custom iterator as below:

```java
class CustomJestHttpClient extends JestHttpClient {
    private final static Logger log = LoggerFactory.getLogger(CustomJestHttpClient.class);
    private final AtomicReference<Pair<Integer, Iterator<String>>> serverPoolReference =
            new AtomicReference<Pair<Integer, Iterator<String>>>(Pair.<Integer, Iterator<String>>of(0, ImmutableSet.<String>of().iterator()));

    @Override
    public void setServers(Set<String> servers) {
        serverPoolReference.set(Pair.of(servers.size(), /* TODO CREATE CUSTOM ITERATOR HERE*/));

        if (servers.isEmpty()) {
            log.warn("No servers are currently available to connect.");
        } else if (log.isDebugEnabled()) {
            log.debug("Server pool was updated to contain {} servers.", servers.size());
        }
    }

    // needs to be overridden to actually use this class' serverPoolReference
    @Override
    protected String getNextServer() {
        Iterator<String> iterator = serverPoolReference.get().getValue();
        synchronized (iterator) {
            if (iterator.hasNext()) return iterator.next();
            else throw new NoServerConfiguredException("No Server is assigned to client to connect");
        }
    }

    // needs to be overridden to actually use this class' serverPoolReference
    protected int getServerPoolSize() {
        return serverPoolReference.get().getKey();
    }
}
```
I have no idea about the actual iterator logic, though.

> there's no way to tell that our slow node is way behind

This is the main problem, based on what data (that is available through the ES REST interface) would you skip a server?

**Comment by andrejserafim** [comment]
That's quite useful - thanks for the example!

Deciding load is an interesting question indeed. I see 2 options here atm:
1. We observe requests in the client and therefore obtain a local view of how each server is responding. This may work reasonably well if we're hitting all the nodes in the cluster often enough and we can see that one or more of them have not responded yet. This will also work if some of our requests are more expensive than others, we'll go easy on the nodes if they are still dealing with them.
2. We can look at queues in the node stats. Now here it gets a little more tricky. But in my use case all the requests are using the bulk api. Therefore looking at the bulk queue in the node would be a good indication of whether it's falling behind.

wdyt?

**Comment by kramer** [comment]
Yeah I had an idea similar to your first point which goes like:

* add a class variable to `CustomHttpClient` of a thread safe data structure type which can hold <ServerUri,AverageExecutionTime> pairs (maybe dictionary?) - i'll call this `servers`
* override `setServers`, `getNextServer`, and `getServerPoolSize` to use `servers`
* override execute methods to measure execution time and update the average execution time for the used server in `servers`
* modify `getNextServer` to select servers with lower average times.

The last point is still tricky and error prone. If you always select the fastest server the slower ones will never be used and therefore their average will never be updated. You could add another field to `servers`, say called, `requestsCount` which is the number of times a server was used, then you could try to work out a "preference score" combining `averageExecutionTime` and `requestsCount` - but yeah you see the hole only goes deeper. There is also the concern of how reliable client side time measurements would be, after all it's HTTP.

Your second point can be done by customising the node checker to call nodes stats api. My two concerns would be:
1. if looking into *that* queue stat is really indicative of the slowness you are experiencing and
2. if that info would be really effective - because:
  * you would only get refreshes for that stat at node checker's run intervals - let's say 5 mins
  * assume you have 3 nodes X,Y,Z. 1 of them (Z) had the longest queue so you decided to kick it from jest's pool. pool now has X and Y.
  * within the next 10 seconds you made one bulk request to X and another to Y, which "filled" their queues - and in the meantime since Z was not used it's queue was processed and is now empty.
  * you're left with 2 slow nodes and 1 unutilized node for the next 4m50s.
