### ISSUE TITLE
Add a NestedAggregation 

### ISSUE THREAD

**Issue by pjo256** [searchbox-io/Jest#325]
Given the following query, 

```
{
 "aggregations" : {
   "top-level" : {
      "terms" : {
        "field" : "foo"
      },
      "aggregations" : {
        "nested" : {
          "nested" : {
            "path" : "bar"
          },
          "aggregations" : {
            "leaf-level" : {
              "avg" : {
                "field" : "bar.baz"
              }
            }
          }
        }
      }
    }
  }
}
```

and result 

```
{
  "key": "top-level",
  "buckets": [
        {
          "key": "rng",
          "doc_count": 4,
          "nested": {
            "doc_count": 8,
            "leaf-level": {
              "value": 10
            }
          }
        }
  ]
}
```

there is no way to parse out the "nested" subaggregation using typed `Aggregation`s

**Comment by marcelalburg** [comment]
It's not possible to use the new feature top_hits aggregation with source. 

i think, it's the same like this thread - nested aggs.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html

Thanks
Marcel

**Comment by kdh6429** [comment]
+1

**Comment by jpblair** [comment]
+1

**Comment by jpblair** [comment]
@pjo256 Not sure if this helps, but I've found that even without a proper `NestedAggregation `type, I was able to use the generic `getAggregation()` and provide `RootAggregation `as the class argument.  That then allows me to get the aggregation associated with the `NestedAggregation` (in your case, `nested`, if I understand your original question correctly) using the standard getters.

And then in response to myself regarding `ReverseNestedAggregation`, I believe the `getAggregation()` method just uses Gson behind the scenes, so if you give it a class that has the fields that you need, then it should be okay.  In my case, I used `FilterAggregation` (since it has a `getCount()` method), and it seems to be working for my use case.

Even though these workarounds seem to get the job done, it's definitely hacky to be using the incorrect `Aggregation` type.  Not sure why Jest doesn't have these two aggregation types out of the box.  Please correct me if they do in fact exist and I just missed them.
