### ISSUE TITLE
Cannot get result field with getHits() when specified field.

### ISSUE THREAD

**Issue by kdh6429** [searchbox-io/Jest#339]
```
       searchSourceBuilder = new SearchSourceBuilder().query(...);
        search = new Search.Builder(searchSourceBuilder.toString())
                                        // multiple index or types can be added.
                                        .addIndex("pIndex")
                                        .addType( "myType")
                                        .build();

        result = client.execute(search);

        List< Hit< ActivityObj, Void>> hits = result.getHits( ActivityObj.class);
        for ( SearchResult.Hit hit: hits) {
            if( hit==null) logger.info(" null");
            else {
                ActivityObj objectSource = (ActivityObj)hit.source;
                logger.info( "hits : " + objectSource.getName());
            }
        }
```

It works well BUT I tried to get only few field that I specified like

SearchSourceBuilder().query(...)**.fields("field1", "field2");**

It doesn't work as expected.
Since result data will be in 'filed' not in '_source', I cannot get field data with getHits(). Any Idea of this?

ps. Why is getSourceAsObjectList deprecated and getHits() is recommand? getHits() needs much more code than getSourceAsObjectList to contain data in map or list.

**Comment by ryanrupp** [comment]
I believe this is the same issue as https://github.com/searchbox-io/Jest/issues/157 that field extraction isn't supported (instead of _source). I ran into a similar problem where actually I only wanted the document ID + highlight information (don't need the _source) but since there's a null check on source when extracting a hit if the _source isn't populated then the entire Hit object doesn't get populated. See the null check here - https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/SearchResult.java#L103 - supporting fields would be larger fix but seems like for the use case I have it would just be removing the null check!

**Comment by ryanrupp** [comment]
Submitted a pull request to fix the issue I described - https://github.com/searchbox-io/Jest/pull/400 - however it is different than trying to map fields to a POJO via getHits since it's only the id/version.
