### ISSUE TITLE
Move to Java 7

### ISSUE THREAD

**Issue by gsmet** [searchbox-io/Jest#423]
Hi!

I was wondering if we could move to Java 7 for the next release of Jest? It might be handy to avoid this sort of issues: https://github.com/searchbox-io/Jest/issues/412 : we could use try with resources.

I'll propose a PR if you think it's a good idea.

-- 
Guillaume

**Comment by ferhatsb** [comment]
@gsmet I think, due to a long break at our release cycle (not happy with it), we should keep Java 6 and make a release with some of the issues fixed to improve stability 

But as you said moving to 7 is a must (actually even 8 is getting old) therefore after next release we can quickly create another release with only 7 move, 

Does it make sense ?

**Comment by gsmet** [comment]
@ferhatsb yes, makes sense!

**Comment by ferhatsb** [comment]
Done, from 2.4 min version is java 7.
