### ISSUE TITLE
Bulk index to AWS elasticsearch with gzip enabled returns error

### ISSUE THREAD

**Issue by kliakos** [searchbox-io/Jest#555]
Looks like AWS does not support gzip request body in the _bulk API? However gzip response in the _search API is supported. Anyone facing the same issue?

ES version used:  5.3

```
{
    "root_cause": [
        {
            "type": "json_parse_exception",
            "reason": "Illegal character ((CTRL-CHAR, code 31)): only regular white space (\\r, \\n, \\t) is allowed between tokens\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@208f7d36; line: 1, column: 2]"
        }
    ],
    "type": "json_parse_exception",
    "reason": "Illegal character ((CTRL-CHAR, code 31)): only regular white space (\\r, \\n, \\t) is allowed between tokens\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@208f7d36; line: 1, column: 2]"
}
```

**Comment by jmlw** [comment]
Are you sure that gzip is supported by AWS Elasticsearch Service on any api? My understanding is this is a cluster configuration setting that AWS hides behind their service implementation, and is not accessible. I did see a thread on the AWS forums where people are still requesting the ability to use gzip on their hosted clusters (https://forums.aws.amazon.com/thread.jspa?threadID=223784). It may be that gzip from AWS ES Service is not supported at all, since it's a cluster setting and not a domain (or index) setting.

**Comment by kliakos** [comment]
From what I read in the AWS forums, this is actually not supported by AWS yet. Not an issue of the Jest lib for sure.
