### ISSUE TITLE
Add in capability to query whilst doing a reindex

### ISSUE THREAD

**Issue by CountCodeula** [searchbox-io/Jest#599]
Currently, there is no simple way to add an ElasticSearch query in the Jest Reindex API. This is supported in Kibana and is in the ElasticSearch documentation: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

I found a way around this by extending the GenericResultAbstractAction class and formatting the query in the exact format that ES expects. I then put the query in the source parameter of the Reindex.Build() method:

public String reindexData(String sourceIndex, String destIndex, final QueryBuilder qb) {
   ImmutableMap<String, Object> sourceMap = ImmutableMap.of("index", sourceIndex, "query", 
   qb.toString().replaceAll("\\\\n", ""));
   ImmutableMap<String, Object> destMap = ImmutableMap.of("index", destIndex);

   MyReindex reindex = new MyReindex.Builder(sourceMap, destMap)
                .refresh(true)
                .waitForCompletion(false)
                .conflicts("proceed")
                .size(5000L)
                .build();

   JestResult result = handleResult(reindex);
   String task = result.getJsonString();
   ...
   }

**Comment by musabgelisgen** [comment]
Thank you for the suggestions. This feature will be added to the next releases Jest 5.3.4 and 6.3.1 with slight changes: Instead of extending the GenericResultAbstractAction class and formatting the query, getData(Gson gson) method is overridden in Reindex class. Therefore, now it is possible to add a query by

- a JSON formatted String
- a Map of String and Objects (using nested Map<K,V> objects)
- `QueryBuilders.termQuery(name, value).toString()`.
